export const API_URL = "https://api.openweathermap.org/data/2.5/weather?q=";
export const API_KEY = "fd48bdf8a8b87b3c140f17625f4e2d57"; // Ваш API ключ
export const cities = [
    { "name": "New York", "country": "USA" },
    { "name": "London", "country": "UK" },
    { "name": "Tokyo", "country": "Japan" },
    { "name": "Paris", "country": "France" },
    { "name": "Sydney", "country": "Australia" },
    { "name": "Moscow", "country": "Russia" },
    { "name": "Berlin", "country": "Germany" },
    { "name": "Toronto", "country": "Canada" },
    { "name": "Buenos Aires", "country": "Argentina" },
    { "name": "Cape Town", "country": "South Africa" },
    { "name": "Beijing", "country": "China" },
    { "name": "Seoul", "country": "South Korea" },
    { "name": "Mumbai", "country": "India" },
    { "name": "Dubai", "country": "UAE" },
    { "name": "Rome", "country": "Italy" },
    { "name": "Mexico City", "country": "Mexico" },
    { "name": "São Paulo", "country": "Brazil" },
    { "name": "Madrid", "country": "Spain" },
    { "name": "Los Angeles", "country": "USA" },
    { "name": "Cairo", "country": "Egypt" },
    { "name": "Istanbul", "country": "Turkey" },
    { "name": "Jakarta", "country": "Indonesia" },
    { "name": "Bangkok", "country": "Thailand" },
    { "name": "Lagos", "country": "Nigeria" },
    { "name": "Karachi", "country": "Pakistan" },
    { "name": "Tehran", "country": "Iran" },
    { "name": "Lima", "country": "Peru" },
    { "name": "Athens", "country": "Greece" },
    { "name": "Lisbon", "country": "Portugal" },
    { "name": "Budapest", "country": "Hungary" },
    { "name": "Vienna", "country": "Austria" },
    { "name": "Prague", "country": "Czech Republic" },
    { "name": "Warsaw", "country": "Poland" },
    { "name": "Dublin", "country": "Ireland" },
    { "name": "Helsinki", "country": "Finland" },
    { "name": "Stockholm", "country": "Sweden" },
    { "name": "Oslo", "country": "Norway" },
    { "name": "Brussels", "country": "Belgium" },
    { "name": "Zurich", "country": "Switzerland" },
    { "name": "Amsterdam", "country": "Netherlands" },
    { "name": "Reykjavik", "country": "Iceland" },
    { "name": "Santiago", "country": "Chile" },
    { "name": "Bogota", "country": "Colombia" },
    { "name": "Manila", "country": "Philippines" },
    { "name": "Kuala Lumpur", "country": "Malaysia" },
    { "name": "Singapore", "country": "Singapore" },
    { "name": "Hanoi", "country": "Vietnam" },
    { "name": "Kathmandu", "country": "Nepal" },
    { "name": "Riyadh", "country": "Saudi Arabia" },
    { "name": "Casablanca", "country": "Morocco" },
    { "name": "Nairobi", "country": "Kenya" }
  ];

  export const redCross = 'https://media.istockphoto.com/id/1695982629/vector/red-cross-mark.jpg?s=612x612&w=0&k=20&c=svdE5z8cIP2RcgBaKbUdzh63P-83NJlXavKboMsmeyY='
  export const greenBird = 'https://img.freepik.com/premium-vector/vector-illustration-green-tick-mark-with-textured-edges-isolated-green-checkmark_714710-227.jpg'